// Code generated by mkbuiltin.go. DO NOT EDIT.

package typecheck

import (
	"cmd/compile/internal/types"
	"cmd/internal/src"
)

// Not inlining this function removes a significant chunk of init code.
//
//go:noinline
func newSig(params, results []*types.Field) *types.Type {
	return types.NewSignature(nil, params, results)
}

func params(tlist ...*types.Type) []*types.Field {
	flist := make([]*types.Field, len(tlist))
	for i, typ := range tlist {
		flist[i] = types.NewField(src.NoXPos, nil, typ)
	}
	return flist
}

var runtimeDecls = [...]struct {
	name string
	tag  int
	typ  int
}{
	{"isolateRejectEffect", funcTag, 1},
	{"isolateCheckEffectCall", funcTag, 3},
	{"isolateCheckEffectClosure", funcTag, 6},
	{"isolatePrintBegin", funcTag, 8},
	{"isolatePrintEnd", funcTag, 9},
	{"newobject", funcTag, 12},
	{"mallocgc", funcTag, 15},
	{"panicdivide", funcTag, 9},
	{"panicshift", funcTag, 9},
	{"panicmakeslicelen", funcTag, 9},
	{"panicmakeslicecap", funcTag, 9},
	{"throwinit", funcTag, 9},
	{"panicwrap", funcTag, 9},
	{"gopanic", funcTag, 17},
	{"gorecover", funcTag, 18},
	{"goschedguarded", funcTag, 9},
	{"goPanicIndex", funcTag, 19},
	{"goPanicIndexU", funcTag, 21},
	{"goPanicSliceAlen", funcTag, 19},
	{"goPanicSliceAlenU", funcTag, 21},
	{"goPanicSliceAcap", funcTag, 19},
	{"goPanicSliceAcapU", funcTag, 21},
	{"goPanicSliceB", funcTag, 19},
	{"goPanicSliceBU", funcTag, 21},
	{"goPanicSlice3Alen", funcTag, 19},
	{"goPanicSlice3AlenU", funcTag, 21},
	{"goPanicSlice3Acap", funcTag, 19},
	{"goPanicSlice3AcapU", funcTag, 21},
	{"goPanicSlice3B", funcTag, 19},
	{"goPanicSlice3BU", funcTag, 21},
	{"goPanicSlice3C", funcTag, 19},
	{"goPanicSlice3CU", funcTag, 21},
	{"goPanicSliceConvert", funcTag, 19},
	{"printbool", funcTag, 22},
	{"printfloat64", funcTag, 24},
	{"printfloat32", funcTag, 26},
	{"printint", funcTag, 28},
	{"printhex", funcTag, 30},
	{"printuint", funcTag, 30},
	{"printcomplex128", funcTag, 32},
	{"printcomplex64", funcTag, 34},
	{"printstring", funcTag, 1},
	{"printquoted", funcTag, 1},
	{"printpointer", funcTag, 35},
	{"printuintptr", funcTag, 3},
	{"printiface", funcTag, 35},
	{"printeface", funcTag, 35},
	{"printslice", funcTag, 35},
	{"printnl", funcTag, 9},
	{"printsp", funcTag, 9},
	{"printlock", funcTag, 9},
	{"printunlock", funcTag, 9},
	{"concatstring2", funcTag, 38},
	{"concatstring3", funcTag, 39},
	{"concatstring4", funcTag, 40},
	{"concatstring5", funcTag, 41},
	{"concatstrings", funcTag, 43},
	{"concatbyte2", funcTag, 45},
	{"concatbyte3", funcTag, 46},
	{"concatbyte4", funcTag, 47},
	{"concatbyte5", funcTag, 48},
	{"concatbytes", funcTag, 49},
	{"cmpstring", funcTag, 50},
	{"intstring", funcTag, 53},
	{"slicebytetostring", funcTag, 54},
	{"slicebytetostringtmp", funcTag, 55},
	{"slicerunetostring", funcTag, 58},
	{"stringtoslicebyte", funcTag, 59},
	{"stringtoslicerune", funcTag, 62},
	{"slicecopy", funcTag, 63},
	{"decoderune", funcTag, 64},
	{"countrunes", funcTag, 65},
	{"convT", funcTag, 66},
	{"convTnoptr", funcTag, 66},
	{"convT16", funcTag, 68},
	{"convT32", funcTag, 70},
	{"convT64", funcTag, 71},
	{"convTstring", funcTag, 72},
	{"convTslice", funcTag, 75},
	{"assertE2I", funcTag, 76},
	{"assertE2I2", funcTag, 76},
	{"panicdottypeE", funcTag, 77},
	{"panicdottypeI", funcTag, 77},
	{"panicnildottype", funcTag, 6},
	{"typeAssert", funcTag, 76},
	{"interfaceSwitch", funcTag, 78},
	{"ifaceeq", funcTag, 80},
	{"efaceeq", funcTag, 80},
	{"panicrangestate", funcTag, 8},
	{"deferrangefunc", funcTag, 18},
	{"rand", funcTag, 81},
	{"rand32", funcTag, 82},
	{"isolateGetOwner", funcTag, 83},
	{"makemap64", funcTag, 85},
	{"makemap", funcTag, 86},
	{"makemap_small", funcTag, 87},
	{"mapaccess1", funcTag, 88},
	{"mapaccess1_fast32", funcTag, 89},
	{"mapaccess1_fast64", funcTag, 90},
	{"mapaccess1_faststr", funcTag, 91},
	{"mapaccess1_fat", funcTag, 92},
	{"mapaccess2", funcTag, 93},
	{"mapaccess2_fast32", funcTag, 94},
	{"mapaccess2_fast64", funcTag, 95},
	{"mapaccess2_faststr", funcTag, 96},
	{"mapaccess2_fat", funcTag, 97},
	{"mapassign", funcTag, 88},
	{"mapassign_fast32", funcTag, 89},
	{"mapassign_fast32ptr", funcTag, 98},
	{"mapassign_fast64", funcTag, 90},
	{"mapassign_fast64ptr", funcTag, 98},
	{"mapassign_faststr", funcTag, 91},
	{"mapIterStart", funcTag, 99},
	{"mapdelete", funcTag, 99},
	{"mapdelete_fast32", funcTag, 100},
	{"mapdelete_fast64", funcTag, 101},
	{"mapdelete_faststr", funcTag, 102},
	{"mapIterNext", funcTag, 103},
	{"mapclear", funcTag, 104},
	{"isolateMapLen", funcTag, 105},
	{"makechan64", funcTag, 107},
	{"makechan", funcTag, 108},
	{"chanrecv1", funcTag, 110},
	{"chanrecv2", funcTag, 111},
	{"chansend1", funcTag, 113},
	{"closechan", funcTag, 114},
	{"chanlen", funcTag, 115},
	{"chancap", funcTag, 115},
	{"writeBarrier", varTag, 117},
	{"typedmemmove", funcTag, 118},
	{"typedmemclr", funcTag, 119},
	{"typedslicecopy", funcTag, 120},
	{"selectnbsend", funcTag, 121},
	{"selectnbrecv", funcTag, 122},
	{"selectsetpc", funcTag, 123},
	{"selectgo", funcTag, 124},
	{"block", funcTag, 9},
	{"makeslice", funcTag, 125},
	{"makeslice64", funcTag, 126},
	{"makeslicecopy", funcTag, 127},
	{"growslice", funcTag, 129},
	{"growsliceBuf", funcTag, 130},
	{"growsliceBufNoAlias", funcTag, 130},
	{"growsliceNoAlias", funcTag, 129},
	{"unsafeslicecheckptr", funcTag, 131},
	{"panicunsafeslicelen", funcTag, 9},
	{"panicunsafeslicenilptr", funcTag, 9},
	{"unsafestringcheckptr", funcTag, 132},
	{"panicunsafestringlen", funcTag, 9},
	{"panicunsafestringnilptr", funcTag, 9},
	{"moveSlice", funcTag, 133},
	{"moveSliceNoScan", funcTag, 134},
	{"moveSliceNoCap", funcTag, 135},
	{"moveSliceNoCapNoScan", funcTag, 136},
	{"memmove", funcTag, 137},
	{"memclrNoHeapPointers", funcTag, 138},
	{"memclrHasPointers", funcTag, 138},
	{"memequal", funcTag, 139},
	{"memequal0", funcTag, 140},
	{"memequal8", funcTag, 140},
	{"memequal16", funcTag, 140},
	{"memequal32", funcTag, 140},
	{"memequal64", funcTag, 140},
	{"memequal128", funcTag, 140},
	{"f32equal", funcTag, 140},
	{"f64equal", funcTag, 140},
	{"c64equal", funcTag, 140},
	{"c128equal", funcTag, 140},
	{"strequal", funcTag, 140},
	{"interequal", funcTag, 140},
	{"nilinterequal", funcTag, 140},
	{"memhash", funcTag, 141},
	{"memhash0", funcTag, 142},
	{"memhash8", funcTag, 142},
	{"memhash16", funcTag, 142},
	{"memhash32", funcTag, 142},
	{"memhash64", funcTag, 142},
	{"memhash128", funcTag, 142},
	{"f32hash", funcTag, 142},
	{"f64hash", funcTag, 142},
	{"c64hash", funcTag, 142},
	{"c128hash", funcTag, 142},
	{"strhash", funcTag, 142},
	{"interhash", funcTag, 142},
	{"nilinterhash", funcTag, 142},
	{"int64div", funcTag, 143},
	{"uint64div", funcTag, 144},
	{"int64mod", funcTag, 143},
	{"uint64mod", funcTag, 144},
	{"float64toint64", funcTag, 145},
	{"float64touint64", funcTag, 146},
	{"float64touint32", funcTag, 147},
	{"int64tofloat64", funcTag, 148},
	{"int64tofloat32", funcTag, 149},
	{"uint64tofloat64", funcTag, 150},
	{"uint64tofloat32", funcTag, 151},
	{"uint32tofloat64", funcTag, 152},
	{"complex128div", funcTag, 153},
	{"racefuncenter", funcTag, 3},
	{"racefuncexit", funcTag, 9},
	{"raceread", funcTag, 3},
	{"racewrite", funcTag, 3},
	{"racereadrange", funcTag, 154},
	{"racewriterange", funcTag, 154},
	{"msanread", funcTag, 154},
	{"msanwrite", funcTag, 154},
	{"msanmove", funcTag, 155},
	{"asanread", funcTag, 154},
	{"asanwrite", funcTag, 154},
	{"checkptrAlignment", funcTag, 156},
	{"checkptrArithmetic", funcTag, 158},
	{"libfuzzerTraceCmp1", funcTag, 159},
	{"libfuzzerTraceCmp2", funcTag, 160},
	{"libfuzzerTraceCmp4", funcTag, 161},
	{"libfuzzerTraceCmp8", funcTag, 162},
	{"libfuzzerTraceConstCmp1", funcTag, 159},
	{"libfuzzerTraceConstCmp2", funcTag, 160},
	{"libfuzzerTraceConstCmp4", funcTag, 161},
	{"libfuzzerTraceConstCmp8", funcTag, 162},
	{"libfuzzerHookStrCmp", funcTag, 163},
	{"libfuzzerHookEqualFold", funcTag, 163},
	{"addCovMeta", funcTag, 165},
	{"x86HasAVX", varTag, 13},
	{"x86HasFMA", varTag, 13},
	{"x86HasPOPCNT", varTag, 13},
	{"x86HasSSE41", varTag, 13},
	{"armHasVFPv4", varTag, 13},
	{"arm64HasATOMICS", varTag, 13},
	{"loong64HasLAMCAS", varTag, 13},
	{"loong64HasLAM_BH", varTag, 13},
	{"loong64HasDBAR_HINTS", varTag, 13},
	{"loong64HasLSX", varTag, 13},
	{"riscv64HasZbb", varTag, 13},
	{"asanregisterglobals", funcTag, 138},
	{"KeepAlive", funcTag, 17},
	{"isolateEnterMetadata", funcTag, 83},
	{"isolateLeaveMetadata", funcTag, 3},
	{"isolateRejectMetadataAPI", funcTag, 1},
	{"isolateCheckMetadataReceiver", funcTag, 166},
	{"isolateCheckMetadataDescriptor", funcTag, 35},
	{"isolateCheckMetadataCall", funcTag, 3},
	{"isolateCheckMetadataClosure", funcTag, 6},
	{"isolateCheckHeapAccess", funcTag, 167},
	{"isolateCheckHeapGlobalRead", funcTag, 168},
	{"isolateCheckHeapAtomicCall", funcTag, 169},
	{"isolateCheckHeapSelect", funcTag, 170},
	{"isolateCheckHeapStrings", funcTag, 171},
	{"isolatePublishMessageInfos", funcTag, 35},
	{"isolateCheckHeapMap", funcTag, 172},
	{"isolateCheckHeapMapKey", funcTag, 173},
	{"isolateCheckHeapReference", funcTag, 174},
	{"isolateCheckHeapStackReference", funcTag, 6},
	{"isolateCheckHeapMove", funcTag, 77},
	{"isolateCheckHeapStackMove", funcTag, 174},
	{"isolateCheckHeapCopy", funcTag, 175},
	{"isolateCheckHeapSliceCopy", funcTag, 176},
	{"isolateCheckHeapInterfaceEqual", funcTag, 173},
}

func runtimeTypes() []*types.Type {
	var typs [177]*types.Type
	typs[0] = types.Types[types.TSTRING]
	typs[1] = newSig(params(typs[0]), nil)
	typs[2] = types.Types[types.TUINTPTR]
	typs[3] = newSig(params(typs[2]), nil)
	typs[4] = types.ByteType
	typs[5] = types.NewPtr(typs[4])
	typs[6] = newSig(params(typs[5]), nil)
	typs[7] = types.Types[types.TINT]
	typs[8] = newSig(params(typs[7]), nil)
	typs[9] = newSig(nil, nil)
	typs[10] = types.Types[types.TANY]
	typs[11] = types.NewPtr(typs[10])
	typs[12] = newSig(params(typs[5]), params(typs[11]))
	typs[13] = types.Types[types.TBOOL]
	typs[14] = types.Types[types.TUNSAFEPTR]
	typs[15] = newSig(params(typs[2], typs[5], typs[13]), params(typs[14]))
	typs[16] = types.Types[types.TINTER]
	typs[17] = newSig(params(typs[16]), nil)
	typs[18] = newSig(nil, params(typs[16]))
	typs[19] = newSig(params(typs[7], typs[7]), nil)
	typs[20] = types.Types[types.TUINT]
	typs[21] = newSig(params(typs[20], typs[7]), nil)
	typs[22] = newSig(params(typs[13]), nil)
	typs[23] = types.Types[types.TFLOAT64]
	typs[24] = newSig(params(typs[23]), nil)
	typs[25] = types.Types[types.TFLOAT32]
	typs[26] = newSig(params(typs[25]), nil)
	typs[27] = types.Types[types.TINT64]
	typs[28] = newSig(params(typs[27]), nil)
	typs[29] = types.Types[types.TUINT64]
	typs[30] = newSig(params(typs[29]), nil)
	typs[31] = types.Types[types.TCOMPLEX128]
	typs[32] = newSig(params(typs[31]), nil)
	typs[33] = types.Types[types.TCOMPLEX64]
	typs[34] = newSig(params(typs[33]), nil)
	typs[35] = newSig(params(typs[10]), nil)
	typs[36] = types.NewArray(typs[4], 64)
	typs[37] = types.NewPtr(typs[36])
	typs[38] = newSig(params(typs[37], typs[0], typs[0]), params(typs[0]))
	typs[39] = newSig(params(typs[37], typs[0], typs[0], typs[0]), params(typs[0]))
	typs[40] = newSig(params(typs[37], typs[0], typs[0], typs[0], typs[0]), params(typs[0]))
	typs[41] = newSig(params(typs[37], typs[0], typs[0], typs[0], typs[0], typs[0]), params(typs[0]))
	typs[42] = types.NewSlice(typs[0])
	typs[43] = newSig(params(typs[37], typs[42]), params(typs[0]))
	typs[44] = types.NewSlice(typs[4])
	typs[45] = newSig(params(typs[37], typs[0], typs[0]), params(typs[44]))
	typs[46] = newSig(params(typs[37], typs[0], typs[0], typs[0]), params(typs[44]))
	typs[47] = newSig(params(typs[37], typs[0], typs[0], typs[0], typs[0]), params(typs[44]))
	typs[48] = newSig(params(typs[37], typs[0], typs[0], typs[0], typs[0], typs[0]), params(typs[44]))
	typs[49] = newSig(params(typs[37], typs[42]), params(typs[44]))
	typs[50] = newSig(params(typs[0], typs[0]), params(typs[7]))
	typs[51] = types.NewArray(typs[4], 4)
	typs[52] = types.NewPtr(typs[51])
	typs[53] = newSig(params(typs[52], typs[27]), params(typs[0]))
	typs[54] = newSig(params(typs[37], typs[5], typs[7]), params(typs[0]))
	typs[55] = newSig(params(typs[5], typs[7]), params(typs[0]))
	typs[56] = types.RuneType
	typs[57] = types.NewSlice(typs[56])
	typs[58] = newSig(params(typs[37], typs[57]), params(typs[0]))
	typs[59] = newSig(params(typs[37], typs[0]), params(typs[44]))
	typs[60] = types.NewArray(typs[56], 32)
	typs[61] = types.NewPtr(typs[60])
	typs[62] = newSig(params(typs[61], typs[0]), params(typs[57]))
	typs[63] = newSig(params(typs[11], typs[7], typs[11], typs[7], typs[2]), params(typs[7]))
	typs[64] = newSig(params(typs[0], typs[7]), params(typs[56], typs[7]))
	typs[65] = newSig(params(typs[0]), params(typs[7]))
	typs[66] = newSig(params(typs[5], typs[11]), params(typs[14]))
	typs[67] = types.Types[types.TUINT16]
	typs[68] = newSig(params(typs[67]), params(typs[14]))
	typs[69] = types.Types[types.TUINT32]
	typs[70] = newSig(params(typs[69]), params(typs[14]))
	typs[71] = newSig(params(typs[29]), params(typs[14]))
	typs[72] = newSig(params(typs[0]), params(typs[14]))
	typs[73] = types.Types[types.TUINT8]
	typs[74] = types.NewSlice(typs[73])
	typs[75] = newSig(params(typs[74]), params(typs[14]))
	typs[76] = newSig(params(typs[5], typs[5]), params(typs[5]))
	typs[77] = newSig(params(typs[5], typs[5], typs[5]), nil)
	typs[78] = newSig(params(typs[5], typs[5]), params(typs[7], typs[5]))
	typs[79] = types.NewPtr(typs[2])
	typs[80] = newSig(params(typs[79], typs[14], typs[14]), params(typs[13]))
	typs[81] = newSig(nil, params(typs[29]))
	typs[82] = newSig(nil, params(typs[69]))
	typs[83] = newSig(nil, params(typs[2]))
	typs[84] = types.NewMap(typs[10], typs[10])
	typs[85] = newSig(params(typs[5], typs[27], typs[11]), params(typs[84]))
	typs[86] = newSig(params(typs[5], typs[7], typs[11]), params(typs[84]))
	typs[87] = newSig(nil, params(typs[84]))
	typs[88] = newSig(params(typs[5], typs[84], typs[11]), params(typs[11]))
	typs[89] = newSig(params(typs[5], typs[84], typs[69]), params(typs[11]))
	typs[90] = newSig(params(typs[5], typs[84], typs[29]), params(typs[11]))
	typs[91] = newSig(params(typs[5], typs[84], typs[0]), params(typs[11]))
	typs[92] = newSig(params(typs[5], typs[84], typs[11], typs[5]), params(typs[11]))
	typs[93] = newSig(params(typs[5], typs[84], typs[11]), params(typs[11], typs[13]))
	typs[94] = newSig(params(typs[5], typs[84], typs[69]), params(typs[11], typs[13]))
	typs[95] = newSig(params(typs[5], typs[84], typs[29]), params(typs[11], typs[13]))
	typs[96] = newSig(params(typs[5], typs[84], typs[0]), params(typs[11], typs[13]))
	typs[97] = newSig(params(typs[5], typs[84], typs[11], typs[5]), params(typs[11], typs[13]))
	typs[98] = newSig(params(typs[5], typs[84], typs[14]), params(typs[11]))
	typs[99] = newSig(params(typs[5], typs[84], typs[11]), nil)
	typs[100] = newSig(params(typs[5], typs[84], typs[69]), nil)
	typs[101] = newSig(params(typs[5], typs[84], typs[29]), nil)
	typs[102] = newSig(params(typs[5], typs[84], typs[0]), nil)
	typs[103] = newSig(params(typs[11]), nil)
	typs[104] = newSig(params(typs[5], typs[84]), nil)
	typs[105] = newSig(params(typs[84]), params(typs[7]))
	typs[106] = types.NewChan(typs[10], types.Cboth)
	typs[107] = newSig(params(typs[5], typs[27]), params(typs[106]))
	typs[108] = newSig(params(typs[5], typs[7]), params(typs[106]))
	typs[109] = types.NewChan(typs[10], types.Crecv)
	typs[110] = newSig(params(typs[109], typs[11]), nil)
	typs[111] = newSig(params(typs[109], typs[11]), params(typs[13]))
	typs[112] = types.NewChan(typs[10], types.Csend)
	typs[113] = newSig(params(typs[112], typs[11]), nil)
	typs[114] = newSig(params(typs[112]), nil)
	typs[115] = newSig(params(typs[10]), params(typs[7]))
	typs[116] = types.NewArray(typs[4], 3)
	typs[117] = types.NewStruct([]*types.Field{types.NewField(src.NoXPos, Lookup("enabled"), typs[13]), types.NewField(src.NoXPos, Lookup("pad"), typs[116]), types.NewField(src.NoXPos, Lookup("cgo"), typs[13]), types.NewField(src.NoXPos, Lookup("alignme"), typs[29])})
	typs[118] = newSig(params(typs[5], typs[11], typs[11]), nil)
	typs[119] = newSig(params(typs[5], typs[11]), nil)
	typs[120] = newSig(params(typs[5], typs[11], typs[7], typs[11], typs[7]), params(typs[7]))
	typs[121] = newSig(params(typs[112], typs[11]), params(typs[13]))
	typs[122] = newSig(params(typs[11], typs[109]), params(typs[13], typs[13]))
	typs[123] = newSig(params(typs[79]), nil)
	typs[124] = newSig(params(typs[5], typs[5], typs[79], typs[7], typs[7], typs[13]), params(typs[7], typs[13]))
	typs[125] = newSig(params(typs[5], typs[7], typs[7]), params(typs[14]))
	typs[126] = newSig(params(typs[5], typs[27], typs[27]), params(typs[14]))
	typs[127] = newSig(params(typs[5], typs[7], typs[7], typs[14]), params(typs[14]))
	typs[128] = types.NewSlice(typs[10])
	typs[129] = newSig(params(typs[11], typs[7], typs[7], typs[7], typs[5]), params(typs[128]))
	typs[130] = newSig(params(typs[11], typs[7], typs[7], typs[7], typs[5], typs[11], typs[7]), params(typs[128]))
	typs[131] = newSig(params(typs[5], typs[14], typs[27]), nil)
	typs[132] = newSig(params(typs[14], typs[27]), nil)
	typs[133] = newSig(params(typs[5], typs[5], typs[7], typs[7]), params(typs[5], typs[7], typs[7]))
	typs[134] = newSig(params(typs[2], typs[5], typs[7], typs[7]), params(typs[5], typs[7], typs[7]))
	typs[135] = newSig(params(typs[5], typs[5], typs[7]), params(typs[5], typs[7], typs[7]))
	typs[136] = newSig(params(typs[2], typs[5], typs[7]), params(typs[5], typs[7], typs[7]))
	typs[137] = newSig(params(typs[11], typs[11], typs[2]), nil)
	typs[138] = newSig(params(typs[14], typs[2]), nil)
	typs[139] = newSig(params(typs[14], typs[14], typs[2]), params(typs[13]))
	typs[140] = newSig(params(typs[14], typs[14]), params(typs[13]))
	typs[141] = newSig(params(typs[14], typs[2], typs[2]), params(typs[2]))
	typs[142] = newSig(params(typs[14], typs[2]), params(typs[2]))
	typs[143] = newSig(params(typs[27], typs[27]), params(typs[27]))
	typs[144] = newSig(params(typs[29], typs[29]), params(typs[29]))
	typs[145] = newSig(params(typs[23]), params(typs[27]))
	typs[146] = newSig(params(typs[23]), params(typs[29]))
	typs[147] = newSig(params(typs[23]), params(typs[69]))
	typs[148] = newSig(params(typs[27]), params(typs[23]))
	typs[149] = newSig(params(typs[27]), params(typs[25]))
	typs[150] = newSig(params(typs[29]), params(typs[23]))
	typs[151] = newSig(params(typs[29]), params(typs[25]))
	typs[152] = newSig(params(typs[69]), params(typs[23]))
	typs[153] = newSig(params(typs[31], typs[31]), params(typs[31]))
	typs[154] = newSig(params(typs[2], typs[2]), nil)
	typs[155] = newSig(params(typs[2], typs[2], typs[2]), nil)
	typs[156] = newSig(params(typs[14], typs[5], typs[2]), nil)
	typs[157] = types.NewSlice(typs[14])
	typs[158] = newSig(params(typs[14], typs[157]), nil)
	typs[159] = newSig(params(typs[73], typs[73], typs[20]), nil)
	typs[160] = newSig(params(typs[67], typs[67], typs[20]), nil)
	typs[161] = newSig(params(typs[69], typs[69], typs[20]), nil)
	typs[162] = newSig(params(typs[29], typs[29], typs[20]), nil)
	typs[163] = newSig(params(typs[0], typs[0], typs[20]), nil)
	typs[164] = types.NewArray(typs[4], 16)
	typs[165] = newSig(params(typs[14], typs[69], typs[164], typs[0], typs[7], typs[73], typs[73]), params(typs[69]))
	typs[166] = newSig(params(typs[14]), nil)
	typs[167] = newSig(params(typs[5], typs[2], typs[13]), nil)
	typs[168] = newSig(params(typs[5], typs[2], typs[5], typs[2]), nil)
	typs[169] = newSig(params(typs[2], typs[5], typs[5], typs[5]), nil)
	typs[170] = newSig(params(typs[5], typs[7]), nil)
	typs[171] = newSig(params(typs[42]), nil)
	typs[172] = newSig(params(typs[5], typs[13]), nil)
	typs[173] = newSig(params(typs[5], typs[5], typs[5], typs[13]), nil)
	typs[174] = newSig(params(typs[5], typs[5]), nil)
	typs[175] = newSig(params(typs[5], typs[7], typs[5], typs[7], typs[2]), nil)
	typs[176] = newSig(params(typs[5], typs[5], typs[7], typs[5], typs[7], typs[13]), nil)
	return typs[:]
}

var coverageDecls = [...]struct {
	name string
	tag  int
	typ  int
}{
	{"initHook", funcTag, 1},
}

func coverageTypes() []*types.Type {
	var typs [2]*types.Type
	typs[0] = types.Types[types.TBOOL]
	typs[1] = newSig(params(typs[0]), nil)
	return typs[:]
}
